model_list:
  # Baseten models from model APIs: https://docs.baseten.co/development/model-apis/overview
  # Note: model_name key is lowercase (Claude Code normalizes to lowercase automatically)
  # Baseten model slugs are case sensitive, so we the value must match the exact string


  - model_name: baseten/deepseek-ai/deepseek-v3-0324
    litellm_params:
      model: baseten/deepseek-ai/DeepSeek-V3-0324
      api_key: os.environ/BASETEN_API_KEY
      drop_params: true

  - model_name: baseten/deepseek-ai/deepseek-v3.1
    litellm_params:
      model: baseten/deepseek-ai/DeepSeek-V3.1
      api_key: os.environ/BASETEN_API_KEY
      drop_params: true

  - model_name: baseten/zai-org/glm-4.6
    litellm_params:
      model: baseten/zai-org/GLM-4.6
      api_key: os.environ/BASETEN_API_KEY
      drop_params: true

  - model_name: baseten/zai-org/glm-4.7
    litellm_params:
      model: baseten/zai-org/GLM-4.7
      api_key: os.environ/BASETEN_API_KEY
      drop_params: true

  - model_name: baseten/zai-org/glm-5
    litellm_params:
      model: baseten/zai-org/GLM-5
      api_key: os.environ/BASETEN_API_KEY
      drop_params: true

  - model_name: baseten/moonshotai/kimi-k2-instruct-0905
    litellm_params:
      model: baseten/moonshotai/Kimi-K2-Instruct-0905
      api_key: os.environ/BASETEN_API_KEY
      drop_params: true

  - model_name: baseten/moonshotai/kimi-k2-thinking
    litellm_params:
      model: baseten/moonshotai/Kimi-K2-Thinking
      api_key: os.environ/BASETEN_API_KEY
      drop_params: true

  - model_name: baseten/moonshotai/kimi-k2.5
    litellm_params:
      model: baseten/moonshotai/Kimi-K2.5
      api_key: os.environ/BASETEN_API_KEY
      drop_params: true

  - model_name: baseten/minimaxai/minimax-m2.5
    litellm_params:
      model: baseten/MiniMaxAI/MiniMax-M2.5
      api_key: os.environ/BASETEN_API_KEY
      drop_params: true

  - model_name: baseten/openai/gpt-oss-120b
    litellm_params:
      model: baseten/openai/gpt-oss-120b
      api_key: os.environ/BASETEN_API_KEY
      drop_params: true

  # Map Claude Code default models to Baseten GPT-OSS 120B
  # None of these models are actually used, they are just for suppressing Claude Code internal check errors
  - model_name: claude-haiku-4-5-20251001
    litellm_params:
      model: baseten/openai/gpt-oss-120b
      api_key: os.environ/BASETEN_API_KEY
      drop_params: true

  - model_name: claude-sonnet-4-5-20250929
    litellm_params:
      model: baseten/openai/gpt-oss-120b
      api_key: os.environ/BASETEN_API_KEY
      drop_params: true

  - model_name: claude-opus-4-1-20250514
    litellm_params:
      model: baseten/openai/gpt-oss-120b
      api_key: os.environ/BASETEN_API_KEY
      drop_params: true
